name: torrent_tracker
description: Dart library for implementing Torrent tracker.
version: 1.2.0
# homepage: https://www.example.com
repository: https://github.com/eclipseglory/torrent_tracker
issue_tracker : https://github.com/eclipseglory/torrent_tracker/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bencode_dart: ^1.0.1
  dartorrent_common:
    path : '../../dartorrent_common'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model : ^1.0.1
