name: torrent_tracker
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  bencode_dart: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  torrent_model : ^1.0.0
