name: dtorrent_tracker
description: Http/Https and UDP torrent tracker/scrape Dart library. It's for implementing bittorrent client.
version: 1.3.17
repository: https://github.com/moham96/dtorrent_tracker
issue_tracker: https://github.com/moham96/dtorrent_tracker/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dtorrent_common: ^1.0.5
  b_encode_decode: ^1.0.4
  events_emitter2: ^1.0.3
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
  dtorrent_parser: ^1.0.8
  path: ^1.8.3
